#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 104intersection.py
## File description:
## help me-desu, kek-sama
##

import os, sys, math

def check_opt(opt):
    if opt == 1 or opt == 2 or opt == 3:
        return 0
    else:
        return 1

def calcul_opt(opt, xp, yp, zp, xv, yv, zv, p):
    if opt == 1:
        a = math.pow(xv, 2) + math.pow(yv, 2) + math.pow(zv, 2)
        b = (2 * xp * xv) + (2 * yp * yp) + (2 * zp * zv)
        c = math.pow(xp, 2) + math.pow(yp, 2) + math.pow(zp, 2) - math.pow(p, 2)
    elif opt == 2:
        a = math.pow(xv, 2) + math.pow(yv, 2)
        b = (2 * xp * xv) + (2 * yp * yv)
        c = (math.pow(xp, 2) + math.pow(yp, 2)) - math.pow(p, 2)
    elif opt == 3:
        angle = float((math.pi / 2) - (p * math.pi / 180))
        a = math.pow(xv, 2) + math.pow(yv, 2) - (math.pow(zv, 2) / math.pow(math.tan(angle), 2))
        b = ((2 * xp) * xv) + (2 * yp * yv) - (2 * zp * zv / math.pow(math.tan(angle), 2))
        c = math.pow(xp, 2) + math.pow(yp, 2) - math.pow(zp, 2) / math.pow(math.tan(angle), 2)
    delta = math.pow(b, 2) - 4 * a * c
    if delta > 0:
        x1 = (-b+math.sqrt(delta))/(2*a)
        x2 = (-b-math.sqrt(delta))/(2*a)
        xpx1 = (xv * x1 + xp)
        ypx1 = (yv * x1 + yp)
        zpx1 = (zv * x1 + zp)
        xpx2 = (xv * x2 + xp)
        ypx2 = (yv * x2 + yp)
        zpx2 = (zv * x2 + zp)
        print ("2 intersection points:")
        print ("(%.3f, %.3f, %.3f)" % (xpx1, ypx1, zpx1))
        print ("(%.3f, %.3f, %.3f)" % (xpx2, ypx2, zpx2))
    elif delta == 0:
        if a == 0:
            print ("There is an infinite number of intersection points.")
            sys.exit(0)
        else:
            x1 = float(-b / (2 * a))
            xpx1 = (xv * x1 + xp)
            ypx1 = (yv * x1 + yp)
            zpx1 = (zv * x1 + zp)
        print ("1 intersection point:")
        print ("(%.3f, %.3f, %.3f)" % (xpx1, ypx1, zpx1))
    else:
        print ("No intersection point.")

if len(sys.argv) == 9:
    try:
        opt = int(sys.argv[1])
        xp, yp, zp = int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4])
        xv, yv, zv = int(sys.argv[5]), int(sys.argv[6]), int(sys.argv[7])
        p = int(sys.argv[8])
        if check_opt(opt) == 1:
            sys.exit(84)
    except:
        print ("error, your arguments are invalid")
        sys.exit(84)
    if opt == 1:
        print ("Sphere of radius %d" % (p))
    elif opt == 2:
        print ("Cylinder of radius %d" % (p))
    elif opt == 3:
        print ("Cone with a %d degree angle" % (p))
    print ("Line passing through the point (%d,%d,%d) and parallel to the vector (%d,%d,%d)" % (xp, yp, zp, xv, yv, zv))
    calcul_opt(opt, xp, yp, zp, xv, yv, zv, p)
else:
    print ("error, you need 8 arguments")
    sys.exit(84)